# .github/workflows/auto-comment-issues.yml
name: Auto Comment on Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: peter-evans/commit-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Thank you for opening this issue! We will get back to you soon.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
