# .github/workflows/comment-on-pr-merge.yml
name: Comment on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on merged PR
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The PR has been successfully merged. Thank you for your contribution!'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
